name: Android Test CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout
      - uses: actions/checkout@v4

      # 2. Setup Java
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Setup Android SDK
      - uses: android-actions/setup-android@v3

      # 4. Cache Gradle
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}

      # 5. Grant permission
      - run: chmod +x gradlew

      # 6. Unit Test
      - name: Run Unit Tests
        run: ./gradlew test

      # 7. UI Test
      - name: Run UI Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          target: google_apis
          arch: x86_64

          disable-animations: false

          emulator-options: >
            -no-window
            -no-audio
            -no-boot-anim
            -no-snapshot-save
            -no-snapshot-load
            -gpu swiftshader_indirect
            -memory 2048
            -delay-adb
            -read-only

          emulator-boot-timeout: 600

          script: |
            set -e

            echo "Waiting for device..."
            adb wait-for-device

            echo "Restarting ADB..."
            adb kill-server
            adb start-server
            adb wait-for-device

            echo "Waiting for PackageManager..."

            TIMEOUT=180
            ELAPSED=0

            while true; do
              if adb shell service list | grep -q package; then
                break
              fi

              sleep 3
              ELAPSED=$((ELAPSED+3))

              if [ "$ELAPSED" -ge "$TIMEOUT" ]; then
                echo "Timeout waiting for PackageManager"
                adb logcat -d
                exit 1
              fi
            done

            echo "Device ready!"

            ./gradlew connectedDebugAndroidTest
