name: Android Test CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: android-actions/setup-android@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}

      - run: chmod +x gradlew

      - name: Unit Tests
        run: ./gradlew test --no-daemon

      - name: UI Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86

          disable-animations: true

          emulator-options: >
            -no-window
            -no-audio
            -no-boot-anim
            -no-snapshot-load
            -no-snapshot-save
            -no-camera
            -gpu swiftshader_indirect
            -memory 1024
            -accel off

          emulator-boot-timeout: 900

          script: |
            echo "ADB devices:"
            adb devices

            adb wait-for-device

            adb shell getprop sys.boot_completed

            ./gradlew connectedDebugAndroidTest --no-daemon

